# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def generate_ballot_archive_uuid(apps, schema_editor):
    BallotArchive = apps.get_model('ballot_distributor', 'BallotArchive')
    for ballot_archive in BallotArchive.objects.all():
        ballot_archive.uuid = uuid.uuid4()
        ballot_archive.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('ballot_distributor', '0002_auto_20180311_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotarchive',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=generate_ballot_archive_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='ballotarchive',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name='ballotarchive',
            unique_together=set([('election', 'uuid')]),
        ),
    ]
